### ISSUE TITLE
Lifetime support

### ISSUE THREAD

**Issue by JojiiOfficial** [kaj/ructe#106]
Using lifetime annotations (eg `@(content: Vec<&'static foo>)`) does not work: 
```
warning:    3:@(data: &BaseData, news: Vec<&'static NewsEntry>)
warning:                                  ^ expected ',' or ')'.
```

**Comment by kaj** [comment]
Ah, I think I parse the `'` as a character quote, and thus require matching pairs.  Will investigate.

**Comment by kaj** [comment]
I didn't parse the `'` character at all.  So I have an upcoming fix for at least the `'static` lifetime.  Will investigate named lifetimes as well.
