### ISSUE TITLE
Consider adding custom elements.

### ISSUE THREAD

**Issue by ianpurton** [kaj/ructe#119]
I've being playing with web components in particular https://nordhealth.design/components/ which allows me to create nice looking applications such as https://nordhealth.design/templates/application/

So my ructe templates look like

```rs
@use super::layout_html;
@use crate::layout::SideBar;

@()

@:layout_html("Dashboard", {

    <nord-header slot="header">
        <h1 class="n-typescale-l">Dashboard</h1>
    </nord-header>

    <nord-card class="mb-m">
        <h2 slot="header">Number of HIE's Raised</h2>
        24
    </nord-card>
}, SideBar::Dashboard)
```

However it's a bit unnecessary to have the web components build the UI in the users browser. Most web components in this design system could have been expanded out at compile time as very few have any JavaScript logic.

So my suggestion is to give Ructe users the ability to define their own HTML elements which Ructe then expands out.

i.e. For a card element.

```html
<card>
  <header>The Title</header>
  <body>Some text</body>
</card>
```

Might get converted to 

```html
<div class="card">
  <div class="header">The Title</div>
  <div>Some text</div>
</div>
```

We could give it a fancy name like 'Server side Component hydration'.

**Comment by kaj** [comment]
We kind of have that, but with a slightly different syntax.  If you have a template `card.rs.html` that takes some arguments,

```
@(title: &str, body: &str)
<div class="card"><div class="header">@title</div><div>@body</div></div>
```

You can use that in another template like this:

```
  @:card("The title", "Some text")
```

If it's possible to call a web component from rust, you should be able to wrap that in a function that behaves like a template (you add an initial argument `out: &mut impl Write`), you will be able to call that from a ructe template in the same way.

**Comment by ianpurton** [comment]
I think that works for simple cases. However, say I have HTML embedded in my component like so..

```html
<card padding="0">
  <header>The Title</header>
  <body>
    <form>
      <label for="fname">First name:</label><br>
      <input type="text" id="fname" name="fname"><br>
      <label for="lname">Last name:</label><br>
      <input type="text" id="lname" name="lname">
    </form>
  </body>
</card>
```

So there are 2 things it would be nice to support

1. Nested HTML or nested components.
2. Optional and mandatory attributes.

So in rust I'd like to define a component like for example

```rust
struct Card {
  padding: Option<u32>;
  heading: Heading,
  body: Body
  html: ...
}

struct Body {
  html: ...
}

impl Component for Card {
}
```

Then Ructe handles translating these components into structs which perhaps implement `impl Write`

**Comment by ianpurton** [comment]
Some prior art from Ruby on Rails is here https://viewcomponent.org/

**Comment by ianpurton** [comment]
I think web components are planning some sort of SSR so perhaps not a ructe issue.
