### ISSUE TITLE
Wrong documentation in for calling other templates

### ISSUE THREAD

**Issue by juliankrieger** [kaj/ructe#120]
The [documentation](https://docs.rs/ructe/latest/ructe/Template_syntax/d_Calling_other_templates/index.html) for calling other templates reports having to add a suffix when calling template functions. The given example did not compile for me.

What did compile for me was changing `base_page_html` occurences to just `base_page`. 

Is the original no longer working due to a breaking chance in 0.14?

**Comment by kaj** [comment]
Sorry I lost your issue!

Using `base_page_html` should work, as in `examples/simple/templates/hello_use_templates.rs.html` that is using `super::hello_html` and `super::hello_code_html`, which are created from the files `hello.rs.html` and `hello_code.rs.html`.

The variants without suffixes are just around for backwards compatibility with earlier versions of ructe, I should probably remove them to avoid confusion.
