### ISSUE TITLE
Suppress or fix clippy pedantic lints

### ISSUE THREAD

**Issue by vbrandl** [kaj/ructe#126]
Running clippy with the pedantic lints (`cargo clippy --tests -- -Dclippy::all -Dclippy::pedantic`) on a project using ructe will produce many errors. Most of them are like this:

```
error: used binding `_ructe_out_` which is prefixed with an underscore. A leading underscore signals that a binding will not be used
```

Would you prefer fixing the lints produced by clippy or allow all pedantic lints for the generated code (`#[allow(clippy::pedantic)]`)?

**Comment by kaj** [comment]
The `_ructe_out_` this kind of "intentionally bad" to avoid accidentally having the same variable name used for somtehing in a template, but that is kind of a hack, maybe `ructe_out_` without the preceding dash would be unlikely enough.

Or maybe i should `#[allow()]` the underscore for that specific variable?  If so, only the specific lint should be allowed, not the whole "pedantic" group.

The other lints are probably just new lints I hadn't checked for yet (unless they come from the actual templates).  I havn't really been that active in developing ructe the last year or so, but I should pick it up a bit, and PR:s are wellcome.
