### ISSUE TITLE
Constant used in template is not parsed properly

### ISSUE THREAD

**Issue by wezm** [kaj/ructe#129]
I have a constant:

```rust
pub const TOKEN_VALIDITY_DURATION: Duration = Duration::minutes(10);
```

Which I import and use in a template like:

```
@use crate::web::password_reset::TOKEN_VALIDITY_DURATION;

@(username: &str, link: &str, new_reset_link: &str)
    ⋮
    <p>
        If you don't use this link within @TOKEN_VALIDITY_DURATION.whole_minutes()
    ⋮
````

This results in generated code:

```
TOKEN_.to_html(_ructe_out_)?;
_ructe_out_.write_all(b"VALIDITY_DURATION.whole_minutes()")?;
```

I think the issue might be the second part of `rust_name` does not include uppercase letters. I tried adding them and it fixed the problem. I can submit a PR with the changes if you like.

https://github.com/kaj/ructe/blob/4065b75e69926a8daaaa4510bb971077ea56b4c1/src/expression.rs#L54-L62

**Comment by kaj** [comment]
Thanks!  Yes, your diagnosis seems correct to me, a PR would be great!

(Or I could fix it myself if you no longer have time, since my answer is a week late).

**Comment by wezm** [comment]
I can do it. I've been using a fixed version in my project. I just need to write some tests to open the PR.
