### ISSUE TITLE
can't use internal html curly brackets 

### ISSUE THREAD

**Issue by CoolName69** [kaj/ructe#140]
here my code `<input pattern="[0-9]{6}" />`

and those two curly braces cause error, so how do i get around it ? (if it's possible)

**Comment by kaj** [comment]
To use verbatim curly brackets in the template body, they must be escaped as `@{` and `@}`, as mentioned in [the docs](https://docs.rs/ructe/latest/ructe/Template_syntax/index.html).

So it would look like this: `<input pattern="[0-9]@{6@}" />`.

**Comment by CoolName69** [comment]
thanks. (should've read the docs properly)
