### ISSUE TITLE
end of expression

### ISSUE THREAD

**Issue by ConnyOnny** [kaj/ructe#2]
> Currently ructe, inspired by twirl, uses a special character (@) to signal the start of an expression, but nothing special to signal the end of an expression. This is very nice when writing simple expressions surrounded by whitespace, tags, or anything else that doesn't look like a part of an expression, but it requires ructe to know the syntax of valid rust expressions and it is problematic if an expression should be immediately followed by something that looks like an expressions.
> 
> Should support for an optional — or required — end-of-expression marker be added? Maybe something like {=expression}? Otherwise, the expression parser will need to be improved. If I do and an end-of-expression marker, it will change the syntax of valid templates, so it should probably be decided one way or the other as soon as possible.

How about `@…\n` for simple stuff and `@{…}` for more complicated stuff (where `…` could contain new lines only in the latter case)?

**Comment by ConnyOnny** [comment]
An alternative not using whitespace and looking familiar to many people would be this:
`<?rct … ?>`

A short hand to echo directly:
`<?= … ?>`
or in our case, as we don't have #1 yet:
`<?=(…) … ?>` where the former `…` specifies the context. This could then be made optional in a future version.

For the file beginning, it could be obligatory to start with the exact sequence "<?rct", because we anyway always need a header and in that way a file identification tool can quickly and reliably identify ructe files.

Example:

```rust
<?rct
use models::blog::{Entry, Comment};

template!(entry: &Entry, comments: &[Comment]);
// or something else than "template!", maybe "arguments!"
// I like the "!" because it behaves much like a macro
?>
<!doctype html>
<html>
  <head>
    <title><?=(HTML)entry.title?> - my blog</title>
  </head>
  <body>
    <h1><?rct echo!<HTML>(entry.title) ?></h1>
    <?rct unsafe { echo_raw!(entry.content) } ?>
    <?rct for comment in comments { ?>
      <h2>Comment by <?=(HTML)comment.author?></h2>
      <?rct unsafe { echo_raw!(comment.content) } // I like how we have to use `unsafe` at this *really* unsafe spot. ?>
    <?rct } ?>
  </body>
</html>
```

Advantages
* familiarity to anybody who has used PHP (which is practically anybody who has ever done anything in the web)
* identifying a ructe file programmatically would be easy
* `template`, `echo` and `echo_raw` could probably *actually* be implemented as rust macros
* more visible separation between HTML and Rust code

Disadvantages
* more verbose (or is that an advantage?)
* breaks compatibility (which is fine because ructe is pre-1.0)
* might remind people of PHP :wink:
* something I don't see right now, because it's my suggestion

**Comment by kaj** [comment]
This syntax is also very similar to jsp, so I have considered it.  Part of why I didn't choose it is the verbosity and part is that twirl just fees more natural and ergonomic, so I used that syntax.  However, twirls superiority over jsp might be entirely independent of the syntax.

I have to think about this some more, so let's use this PR as a general discussion thread about syntax in general and expression syntax in particular for ructe.

**Comment by kaj** [comment]
A related thing: I think there is a value in limiting the rust code that can be included in a template.  It may be that I have just seen (and written, I have to admit) way to much java code embedded directly into .jsp files, and maybe developers of today would have better discipline, but I think `@if ...` and `@for ...` is about enough.

Also, not allowing arbitrary whitespace (i.e. newlines) in expressions may be a way to remind template authors to keep expressions reasonably short.  If a more complex expression is needed, maybe that should be in a helper method?

**Comment by kaj** [comment]
I have been testing and using ructe for a while in some projects by now, and I think the basic syntax is nice to work with.  A template engine based on a more jsp- or php-like syntax could be created, but that would be another project.

So I'll just close this issue now.  Thank you for the discussion, @ConnyOnny !

**Comment by Aunmag** [comment]
We could use [rocker](https://github.com/fizzed/rocker)-like [eval expressions](https://github.com/fizzed/rocker/blob/master/docs/SYNTAX.md#eval-expression-):
```sql
-- @(file_name).sql
SELECT * FROM @(schema).@(table);
```
