### ISSUE TITLE
excess newline

### ISSUE THREAD

**Issue by aep** [kaj/ructe#21]
there's an extra newline appended to the output of the template function. Is there a reason for this or can it be removed?

```
@()
Hello World!
```

```
use std::io::{self, Write};
#[cfg_attr(feature="cargo-clippy", allow(useless_attribute))]
#[allow(unused)]
use ::templates::{Html,ToHtml};

pub fn wireless(out: &mut Write)
-> io::Result<()> {
write!(out, "Hello World!\n\n")?;
Ok(())
}

```

**Comment by kaj** [comment]
If you run `cargo test` in `examples/simple`, do the tests fail or succeed?  If they fail and you run windows, it seems we have an unintended target dependency.

**Comment by aep** [comment]
user error. there WAS a newline in the input. my editor confused me. sorry for the noise
