### ISSUE TITLE
Unable to use || && in @if

### ISSUE THREAD

**Issue by kornelski** [kaj/ructe#24]
Template containing: 

```
@if true || false {
}
```

does not compile:

> The following warnings were emitted during compilation:

```
warning: Template parse error in "templates/test.rs.html":
warning:    3:@if true || false {
warning:      ^ Error in expression starting here:
warning:    3:@if true || false {
warning:          ^ Error in conditional expression:
warning:    3:@if true || false {
warning:               ^ Expected "{"
warning:    3:@if true || false {
warning:               ^ Char
```

**Comment by kaj** [comment]
Yes, that sounds like it should work.   As long as `@foo || bar` still evaluates `@foo` as an expression and ` || bar` as plain text coming after the expression.

Do you want to implement it?

**Comment by kaj** [comment]
This should work as expected now that #28 is merged.
