### ISSUE TITLE
Omit element

### ISSUE THREAD

**Issue by kornelski** [kaj/ructe#30]
I often want to conditionally wrap content in an element, e.g. write `<a>@foo</a>` or `@foo` depending on whether I have a URL to link to.

Current solutions aren't great. I either have to repeat the code that generates the content:

```html
@if let Some(url) = url {
   <a href="@url">@label</a>
} else {
   @label
}
```

or repeat the condition:

```html
@if let Some(url) = url {
   <a href="@url">
}
@label
@if url.is_some() {
   </a>
}
```

which could lead to invalid HTML generated if the second condition wans't exactly matching the first one.

[TAL](https://phptal.org/manual/en/#tal-omit-tag) has a feature for this. It'd be something like this:

```html
<a tal:omit-tag="url.is_none()" href="@url">@label</a>
```

If the condition in the opening tag is false, the closing tag is also removed.

**Comment by kaj** [comment]
I have avoided knowledge of html / xml details in ructe (as opposed to jsp and php, which is pretty much html with xml processing instructions).  With simple content like your example, I actually think the first of your implementations is quite nice.  With more complex content, a possible workaround is to have a template `condlink.rs.html` like this:

```
@(href: Option<&str>, content: Content)
@if let Some(href) = href {
  <a href="@href">@:content()</a>
} else {
  @:content()
}
```

And call that like `@:condlink(optional_url, {Link @description that may be complex})` from other templates.
