### ISSUE TITLE
escaped curly brace emitted twice

### ISSUE THREAD

**Issue by dermetfan** [kaj/ructe#33]
It seems that since 0.4.0, escaped curly braces are emitted twice:

`@{` → `{{`
`@}` → `}}`

---

Not sure if it's worth to open another issue: Is there a way to escape `@`? I had no luck with `@@` so I'm sticking to the HTML entity code for now.

**Comment by kaj** [comment]
Yes, you are right.  Back in #26 , the generated code was changed from `write!(out, "text from template")` to `out.write_all("text from template")`.  But that means that text from template is now just a string and not a format string, and so curly braces no longer needs to be escaped to `{{` internally.

Thank you for your report!

**Comment by kaj** [comment]
Also, the `@@` escape sounds like a good thing, I'll add it.

**Comment by dermetfan** [comment]
Thank you for the quick fix and release, great work!
