### ISSUE TITLE
parse error with <style> tag

### ISSUE THREAD

**Issue by dermetfan** [kaj/ructe#4]
I decided to try ructe for a small web project.

This is a reduced sample that should suffice to reproduce the problem.

`main.rs`:
```rust
include!(concat!(env!("OUT_DIR"), "/templates.rs"));

fn main() {
    templates::style(&mut std::io::stdout()).unwrap();
}
```

`style.rs.html`:
```html
@()

<html>
<head>
<style>
#content {
    color: red;
}
</style>
</head>

<body>
<div id="content">Content!</div>
</body>
</html>
```

This results in a compilation error:
```
error[E0425]: unresolved name `templates::style`
 --> src/main.rs:4:5
  |
4 |     templates::style(&mut std::io::stdout()).unwrap();
  |     ^^^^^^^^^^^^^^^^
```

A more informative message is found in `target/debug/build/<project>/output`:
```
cargo:warning=Template parse error Eof in "/path/to/project/ructe-issue-3/templates/style.rs.html": "{\n    color: red;\n}\n</style>\n</head>\n\n<body>\n<div id=\"content\">Content!</div>\n</body>\n</html>\n"
```

The templates compiles if I remove the content of the `<style>`-tag.

My guess would be that ructe is confused by the curly braces in CSS, as the error message reports an Eof parse error at the first `{`.

**Comment by kaj** [comment]
Yes.  Since the curly braces are used for delimiting blocks they are not allowed unescaped in templates.

Since there is nothing that would explain a block at that position, it would be possible to actually allow raw curly braces there, but the easy solution is to just escape curly brackets like so:

```
<style>
#content @{
    color: red;
@}
</style>
```

**Comment by dermetfan** [comment]
Thanks for the quick clarification! Maybe this should be mentioned in the readme - I couldn't find information on escaping (other than HTML encoding).

**Comment by kaj** [comment]
Yep, it should be in the documentation (such as it is).  I added a paragraph to `README.md`.

**Comment by dermetfan** [comment]
Great, thanks!
