### ISSUE TITLE
How to declare reusable blocks

### ISSUE THREAD

**Issue by mocsy** [kaj/ructe#40]
How to declare reusable blocks?
```
@display(link: &Link) {
<li>@link.url @link.visual</li>;
}
```

> warning: Template parse error in "D:\\Creating\\dev\\pinnaculum\\src\\modules\\navigation\\sidebar.rs.html":
> warning:    6:@display(link: &Link) {
> warning:                            ^ Error in expression starting here:
> warning:    6:@display(link: &Link) {
> warning:                            ^ In expression starting here
> warning:    6:@display(link: &Link) {
> warning:                            ^ Switch
> warning:    6:@display(link: &Link) {
> warning:                            ^ Alt

I plan to use it like this:
<ul>
@for(link in links) {
@:display(link)
}
</ul>

Inspired by https://www.playframework.com/documentation/2.6.x/ScalaTemplates#declaring-reusable-blocks

**Comment by kaj** [comment]
For now, you need to create the resuable blocks as separate templates (e.g.  a `display.rs.html` file) and then import them to the template where you want to use them with e.g `@use super::display`.

Would being able to create "reusable" blocks inside another templates be worthwhile?  If so, they would only be reusable inside the one template where they are declared.

**Comment by kaj** [comment]
I'll consider this answered, and close the issue now.  Feel free to reopen it in case documentation or behavior on this can be improved.
