### ISSUE TITLE
SVG commit was a semver-breaking change

### ISSUE THREAD

**Issue by kornelski** [kaj/ructe#62]
2e4173eead901e2904c7a59d41fee2f8baafb473 renamed template functions, which broke all existing code.

Can you revert the change, or yank 0.7.4 and release it as 0.8?

**Comment by kaj** [comment]
Huh?  I thought the "use name_html as name" lines I had made old code compile?

**Comment by kaj** [comment]
It did not break https://github.com/kaj/fanrs or https://github.com/kaj/rphotos .  Do you have an example of a breakage that you can link to, so I can see what happened?

**Comment by kornelski** [comment]
The breakage is in the commit itself: https://github.com/kaj/ructe/commit/2e4173eead901e2904c7a59d41fee2f8baafb473#diff-c49b37a811fae544bbddf755fe02b94cL9

it was required to change the name of the template function to add `_html` to it. If you need to change code in the examples dir, that's a breaking change :)

**Comment by kornelski** [comment]
Recursive template calls broke:

In `foo.rs.html`:

```
@()

@:foo()
```

results in definition of `foo_html()`, but a call to `foo()`.

**Comment by kaj** [comment]
Oh, I haven't considered the possibility of recursive templates.  Cool!

Ok, I'll revert the 0.7.4 release and release it as 0.8.0 instead.

**Comment by kaj** [comment]
Done, so I hope this is fine now.
