### ISSUE TITLE
Escape dots - end of expression

### ISSUE THREAD

**Issue by Aunmag** [kaj/ructe#64]
I've been migrating from Java to Rust with ructe, and got into a problem which I don't now how to solve. So I have a number of SQL temples like this one, and they cannot be compiled:
```sql
ALTER SEQUENCE @(model.schema).@(model.get_sequence_name())
	OWNED BY @(model.schema).@(model.name).id;
```

I got:
```
error[E0609]: no field `id` on type `std::string::String`
  --> D:\Development\coderator-rs\target\debug\build\coderator-94163fea6e350a38\out\templates\template_create_html.rs:24:12
   |
24 | model.name.id.to_html(&mut out)?;
   |            ^^ unknown field

error: aborting due to previous error

For more information about this error, try `rustc --explain E0609`.
error: could not compile `coderator`.

To learn more, run the command again with --verbose.
```

Please, consider to implement [rocker](https://github.com/fizzed/rocker)-like [eval expressions](https://github.com/fizzed/rocker/blob/master/docs/SYNTAX.md#eval-expression-) from the beast Java template engine I've ever seen. Everything outside `@(...)` should be treated as a template text, not as an expression.

I know that there already was https://github.com/kaj/ructe/issues/2 but I still don't know to make my templates work.

**Comment by kaj** [comment]
You use ructe for sql?  Cool!  :-)

Ah.  The `@model.shema.@model.get_sequence_name()` part should be no problem problem even without the parentesis, but then you have the `@(model.name).id` part.

One way of fixing this would be to say that _if_ an expression starts with an open parenthesis, then it ends when that parenthesis is closed.  That would make your example behave correctly.  And if we just allow the same things inside those parenthesis as we allow in expressions today, I don't see any real down-side.  Does that sound ok to you?

**Comment by Aunmag** [comment]
That sounds awesome! :+1:
