### ISSUE TITLE
Template parse error with lambda and condition

### ISSUE THREAD

**Issue by Aunmag** [kaj/ructe#66]
Can't compile this simple template:
```rust
@()

@Option::None.unwrap_or_else(|| {
    let mut text = String::from("AB");

    if true {
        text.push('C');
    }

    return text;
})
```

It says:
```
warning: Template parse error in "templates\\test.rs.html":
warning:    2:@Option::None.unwrap_or_else(|| {
warning:                                      ^ Error in expression starting here:
```

If I remove the `if` condition, then it will compile.

rustc 1.39.0 (4560ea788 2019-11-04)
cargo 1.39.0 (1c6ec66d5 2019-09-30)
ructe 0.9.0

**Comment by kaj** [comment]
Sorry for the long delay in answering this.

I can confirm this happens.  I don't think I agree that it's a "simple" tempate ...  But since the outer set of braces are allowed in a "value", I guess the inner set should be allowed as well.
