### ISSUE TITLE
Template parse error with newline character

### ISSUE THREAD

**Issue by Aunmag** [kaj/ructe#67]
Can't compile this simple template:
```rust
@()
@("1\n2\n3")
```

It says:
```
warning: Template parse error in "templates\\test.rs.html":
warning:    2:@("1\n2\n3")
warning:      ^ Error in expression starting here:
```

How can I write a string with a new line character?

rustc 1.39.0 (4560ea788 2019-11-04)
cargo 1.39.0 (1c6ec66d5 2019-09-30)
ructe 0.9.0

**Comment by kaj** [comment]
Yes, that's a bug.  [Everything rust accepts in a string](https://doc.rust-lang.org/stable/reference/tokens.html#literals) should be accepted by ructe as well.

I'll fix.
