### ISSUE TITLE
Support unparameterized templates

### ISSUE THREAD

**Issue by mrmonday** [kaj/ructe#75]
Currently, if you have a plain HTML file, eg:

```html
<!doctype html>
<html>
<head>
</head>
<body>
</body>
</html>
```

Ructe gives an error:
```
warning: Template parse error in "templates/test.rs.html":
warning:    1:<!doctype html>
warning:      ^ expected '@('...')' template declaration.
```

It would be great to be able to have a plain HTML file "just work"

**Comment by kaj** [comment]
To make it a template, you need to make it callable by addding `@()` before the content.  Or you can rename the file to `test.html` and handle it as a static file rather than a template.

https://docs.rs/ructe/0.11.4/ructe/Template_syntax/index.html
