### ISSUE TITLE
Cannot use turbofish syntax in template

### ISSUE THREAD

**Issue by OskarPersson** [kaj/ructe#77]
The following template code does not work:

```
<p>@books.into_iter().map(|b| b.title).collect::<Vec<String>>().join(", ")</p>
```

and results in the following error

```
  --> C:\Users\oskar\git\books-rs\target\debug\build\books-rs-44f2c21020dbf42e\out\templates\template_books_html.rs:12:46
   |
12 | books.into_iter().map(|b| b.title).collect.to_html(&mut _ructe_out_)?;
   |                                    ^^^^^^^ help: use parentheses to call the method: `collect()`
```

**Comment by kaj** [comment]
Yes, the turbofish makes the expression to complex to use without enclosing parenthesis.  You can fix it by enclosing the entire expression in parenthesis:

```html
<p>@(books.into_iter().map(|b| b.title).collect::<Vec<String>>().join(", "))</p>
```

The error message for this could be better (as could all error messages from the generated code), but I don't know how to do that.
