### ISSUE TITLE
Allow `else if` conditions

### ISSUE THREAD

**Issue by Aunmag** [kaj/ructe#81]
Can't compile this simple template:
```rust
@()

@if false {
1
} else if false {
2
} else {
3
}
```

It says:
```
warning: Template parse error in "templates\\test.rs.html":
warning:    5:} else if false {
warning:                      ^ Error in expression starting here:
```

If I remove the `else if` condition, then it will compile.

rustc 1.44.0 (49cae5576 2020-06-01)
cargo 1.44.0 (05d080faa 2020-05-06)
ructe 0.11.4

**Comment by kaj** [comment]
Yes, it would clearly be reasonable to support `else if`.  Do you want to attempt a pull request?

Until fixed, it should be simple to work around, like so:

```
@if false {
  1
} else {
  @if false {
    2
  } else {
    3
  }
}
```

**Comment by Aunmag** [comment]
@kaj I'm sorry what do you mean by "attempt a pull request"?

**Comment by kaj** [comment]
> @kaj I'm sorry what do you mean by "attempt a pull request"?

To write the code that fixes it and submit it here on github as a pull request.  If you don't want to, it up for anyone who want to, or I'll fix it in a few days.

**Comment by Aunmag** [comment]
@kaj I'm not sure if I can handle it. It will take some time, and don't have it much for now. So it would be better if somebody else will fix this.

**Comment by kaj** [comment]
Took quite some time for me to get around to it, but I'm on it now.  :-)
