### ISSUE TITLE
How do I call async functions from templates?

### ISSUE THREAD

**Issue by OskarPersson** [kaj/ructe#83]
I'm using actix-web together with sqlx and based on some if-statements inside my templates I want to fetch additional data from the database using some async struct methods.

What is the recommended approach for this (if it's even possible)?

**Comment by kaj** [comment]
A template is compiled to a rust function, and there is no way to make _that_ function `async` (at least currently).  My theory is that rendering the template itself should be done in one (really fast) step after everything is is done and `.await`ed.

I think the only good way to allow calling async functions from inside a template would be to make the template function itself async, which would require a change in `ructe` itself to recognize an `async` keyword somehere in the template definition.  (I do _not_ wish to change all templates to be async functions, as I think that would cost some run-time overhead).
