### ISSUE TITLE
if statement compare values

### ISSUE THREAD

**Issue by mrLSD** [kaj/ructe#9]
Currently imposible compare values at if statment.
For example:
```
@(myval: &str)
@if myval == "test" {...}
error exception
``

```
@(myval: i32)
@if myval > 10 {...}
error exception
``

valid:
```
@(myval: bool)
@if myval {...}
```
or
```
@(myval: &MyStruct)
@if myval.my_method() {...}
```

It is the load on the code and in general it is not convenient.

Do you want to improve?

**Comment by kaj** [comment]
Yes, comparisions in conditionals should be allowed.  Not implemented yet, but should not be to hard to fix ...
