### ISSUE TITLE
Passing values multiple levels when calling other templates

### ISSUE THREAD

**Issue by mathiversen** [kaj/ructe#92]
I have the following scenario where i would like to pass a value through multiple templates. The example below doesn't work as I can't call the parent with `msg` in this case. I can get around this by using &format!("{}", msg), but it would be nice with just using the variable. Not sure if it's a good idea or not, what do you think?

page.rs.html
```
@use super::page_parent_html;
@()
<div>@:parent_html("hello")</div>
```

page_parent.rs.html
```
@use super::page_grand_parent_html;
@(msg: &str)
<div>@:parent_html(msg)</div>
```

page_grand_parent.rs.html
```
@(msg: &str)
<div>@msg</div>
```

**Comment by kaj** [comment]
I assume page_parent should call page_grand_parent rather than itself, but other than that I don't see a problem?  Using a variable when calling a template should not be a problem.

**Comment by mathiversen** [comment]
I did another check just with the example above, (fixed the naming issue), and you're right of course! Not sure what I've done in the other project that got me confused.. Sorry about that :) I'll see if i can reproduce my issue that got me thinking it didn't work in the first place.
