### ISSUE TITLE
Using static files without hash suffixes?

### ISSUE THREAD

**Issue by OskarPersson** [kaj/ructe#96]
How do I use static files without getting the hash suffixes? I want to create the hashes in my Webpack pipeline instead and have problems with source maps if Ructe also adds a suffix

**Comment by kaj** [comment]
If your webpack pipeline gives you a directory of files you can add them all with `StaticFiles::add_files_as(...)`.  But maybe it should handle the case where `to` is empty properly.

If you want to handle each file individually, there is `add_file_as`, converting the releavant part ot the `path` to a `url_name` yourself.
